### ISSUE TITLE
Incompatible with PHP 8.0; 8.2

### ISSUE THREAD

**Issue by khoacoban** [lepidus/doiInSummary#1]
Get error 500 when I enable this plugin.

**Comment by JhonathanLepidus** [comment]
Greetings!

We're grateful you warned us about this problem. We have released [v1.3.1](https://github.com/lepidus/doiInSummary/releases/tag/v1.3.1) which fixes it. Can you check it?

**Comment by diegoabadan** [comment]
The new version is available in the gallery.
Please let us know if any issue.
